### ISSUE TITLE
A few observations

### ISSUE THREAD

**Issue by Cigal33** [garrylachman/react-native-xmrig#4]
At first, using the version before 1.020, I was not able to run a benchmark. Nothing happening, so I didn't benchmark anymore. 
I still was able to do mining from time to time. By default it was using the randomX algo but working maybe 1 time every 6-7 attempt.

I let go about a week. It was the newer version 1.020. I was still having the same problem with randomX. 
But I re-try the Benchmark and this time it was working!! magic! Now the mining is working well using the argon2/chukwav2 algo.

The first run I did was perfect with my phone, with the app open or in the background. I close the app and did a second run. This time, it was fine while the app was open on the screen but each time I go 'off screen' cause the screen/cell phone was getting hot, the app give the error message 'software cause the application to close' (or something similar!)

I do another benchmark and it seem to have resolve this problem so far.

But here's my new observation.... I let the application working in the background all night and when I opened it in the morning, the screen was showing stats from 4 hours ago and was not able to update fast enough to bring it to real time stats. But the cell phone notifications was still showing stats real-time (1350/0 accepted, etc...) and in the app info from 3-4 hours ago (950/0 accepted, etc). 

I had to force quit the app, it was not responding, trying to update but not fast enough. It also cause another problem. The dev % unlock didn't move at all during the night. It was at the exat same place as when I let it for the night. A 8 hours run for nothing? 

Hope my observation may help you.
I'm using a Galaxy S20 FE 5G

-Claude

**Comment by garrylachman** [comment]
The stats are updated and calculated in react native state. I didn't think about the senario that the app running in background for long time, I need to think about refactoring stats and implement it in java native code to handle this.

The xmring binary run as android service while the react native app pulling the stats via http requests. Because of this the miner still run and not dependent on the app itself.

Thank for the feedback, it's helped me to figure out how to refactor some parts of the app.

**Comment by garrylachman** [comment]
Fixed in version 1.0.21

**Comment by tissoudali1** [comment]
App doesn't work  😕

**Comment by Miguelb-crypto** [comment]
I got a problem with the apps.. after benchmark. App close
