### ISSUE TITLE
How to monitor and or, configure settings?

### ISSUE THREAD

**Issue by linuxhp** [garrylachman/react-native-xmrig#9]
I just wanted to know how I can monitor and or, configure settings in the react native xmrig app, in termux? Things like real time mining stats and settings like, cpu-priority, cpu-affinity, and cpu-max-threads-hint? I have xmrig for termux, and of course it has all those options but wondering if any of it is possible with the react native app? I almost forgot, I didn't want to create another issue but I have my wallet address set in the app but it just keeps giving me the "save" option and not the "use" option.

**Comment by garrylachman** [comment]
It's more user friendly option to running xmrig in termux. If you need more customization just use termux/xmrig.

**Comment by linuxhp** [comment]
Ok... I thought so, just wasn't sure. It sure is much easier to use and an
excellent app. Thank you for getting back to me.

**Comment by garrylachman** [comment]
The use option is for set an old address, it's disabled in case that the current wallet is the same you want to use. Use the wallet settings only for change the address, after that its remembers the saved wallet.

About the other settings, every time you press on "start" the config file is overwrited so each change must be implemented in UI and/or default configuration and it's requires compilation

**Comment by DoubleGhosty** [comment]
can you add a option to change the pool ? thx
